version: '2'

networks:
  kafka-net:
    driver: bridge

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
    - kafka-net
    ports:
    - '2181:2181'
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-1:
    image: 'bitnami/kafka:latest'
    networks:
    - kafka-net
    ports:
    - '9092:9092'
    environment:
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.13:9092
    #    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.220.104:9092
    - ALLOW_PLAINTEXT_LISTENER=yes

    depends_on:
    - zookeeper

#  kafka-2:
#    image: 'bitnami/kafka:latest'
#    networks:
#      - kafka-net
#    ports:
#      - '19093:9092'
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.12:9093
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
